var countries = [
    { code: 'af', name: 'Afghanistan' },
    { code: 'al', name: 'Albanien' },
    { code: 'dz', name: 'Algerien' },
    { code: 'as', name: 'Amerikanisch-Samoa' },
    { code: 'ad', name: 'Andorra' },
    { code: 'ao', name: 'Angola' },
    { code: 'ai', name: 'Anguilla' },
    { code: 'aq', name: 'Antarktis' },
    { code: 'ag', name: 'Antigua und Barbuda' },
    { code: 'ar', name: 'Argentinien' },
    { code: 'am', name: 'Armenien' },
    { code: 'aw', name: 'Aruba' },
    { code: 'au', name: 'Australien' },
    { code: 'at', name: 'Österreich' },
    { code: 'az', name: 'Aserbaidschan' },
    { code: 'bs', name: 'Bahamas' },
    { code: 'bh', name: 'Bahrain' },
    { code: 'bd', name: 'Bangladesch' },
    { code: 'bb', name: 'Barbados' },
    { code: 'by', name: 'Weißrussland' },
    { code: 'be', name: 'Belgien' },
    { code: 'bz', name: 'Belize' },
    { code: 'bj', name: 'Benin' },
    { code: 'bm', name: 'Bermuda' },
    { code: 'bt', name: 'Bhutan' },
    { code: 'bo', name: 'Bolivien' },
    { code: 'ba', name: 'Bosnien und Herzegowina' },
    { code: 'bw', name: 'Botswana' },
    { code: 'bv', name: 'Bouvetinsel' },
    { code: 'br', name: 'Brasilien' },
    { code: 'io', name: 'Britisches Territorium im Indischen Ozean' },
    { code: 'bn', name: 'Brunei Darussalam' },
    { code: 'bg', name: 'Bulgarien' },
    { code: 'bf', name: 'Burkina Faso' },
    { code: 'bi', name: 'Burundi' },
    { code: 'kh', name: 'Kambodscha' },
    { code: 'cm', name: 'Kamerun' },
    { code: 'ca', name: 'Kanada' },
    { code: 'cv', name: 'Kap Verde' },
    { code: 'ky', name: 'Kaimaninseln' },
    { code: 'cf', name: 'Zentralafrikanische Republik' },
    { code: 'td', name: 'Tschad' },
    { code: 'cl', name: 'Chile' },
    { code: 'cn', name: 'China' },
    { code: 'cx', name: 'Weihnachtsinsel' },
    { code: 'cc', name: 'Kokosinseln (Keeling)' },
    { code: 'co', name: 'Kolumbien' },
    { code: 'km', name: 'Komoren' },
    { code: 'cg', name: 'Kongo' },
    { code: 'cd', name: 'Kongo, Demokratische Republik' },
    { code: 'ck', name: 'Cookinseln' },
    { code: 'cr', name: 'Costa Rica' },
    { code: 'ci', name: 'Elfenbeinküste' },
    { code: 'hr', name: 'Kroatien' },
    { code: 'cu', name: 'Kuba' },
    { code: 'cy', name: 'Zypern' },
    { code: 'cz', name: 'Tschechische Republik' },
    { code: 'dk', name: 'Dänemark' },
    { code: 'dj', name: 'Dschibuti' },
    { code: 'dm', name: 'Dominica' },
    { code: 'do', name: 'Dominikanische Republik' },
    { code: 'ec', name: 'Ecuador' },
    { code: 'eg', name: 'Ägypten' },
    { code: 'sv', name: 'El Salvador' },
    { code: 'gq', name: 'Äquatorialguinea' },
    { code: 'er', name: 'Eritrea' },
    { code: 'ee', name: 'Estland' },
    { code: 'et', name: 'Äthiopien' },
    { code: 'fk', name: 'Falklandinseln (Malwinen)' },
    { code: 'fo', name: 'Färöer' },
    { code: 'fj', name: 'Fidschi' },
    { code: 'fi', name: 'Finnland' },
    { code: 'fr', name: 'Frankreich' },
    { code: 'gf', name: 'Französisch-Guayana' },
    { code: 'pf', name: 'Französisch-Polynesien' },
    { code: 'tf', name: 'Französische Südgebiete' },
    { code: 'ga', name: 'Gabun' },
    { code: 'gm', name: 'Gambia' },
    { code: 'ge', name: 'Georgien' },
    { code: 'de', name: 'Deutschland' },
    { code: 'gh', name: 'Ghana' },
    { code: 'gi', name: 'Gibraltar' },
    { code: 'gr', name: 'Griechenland' },
    { code: 'gl', name: 'Grönland' },
    { code: 'gd', name: 'Grenada' },
    { code: 'gp', name: 'Guadeloupe' },
    { code: 'gu', name: 'Guam' },
    { code: 'gt', name: 'Guatemala' },
    { code: 'gn', name: 'Guinea' },
    { code: 'gw', name: 'Guinea-Bissau' },
    { code: 'gy', name: 'Guyana' },
    { code: 'ht', name: 'Haiti' },
    { code: 'hm', name: 'Heard und McDonaldinseln' },
    { code: 'va', name: 'Heiliger Stuhl (Vatikanstadt)' },
    { code: 'hn', name: 'Honduras' },
    { code: 'hk', name: 'Hongkong' },
    { code: 'hu', name: 'Ungarn' },
    { code: 'is', name: 'Island' },
    { code: 'in', name: 'Indien' },
    { code: 'id', name: 'Indonesien' },
    { code: 'ir', name: 'Iran' },
    { code: 'iq', name: 'Irak' },
    { code: 'ie', name: 'Irland' },
    { code: 'il', name: 'Israel' },
    { code: 'it', name: 'Italien' },
    { code: 'jm', name: 'Jamaika' },
    { code: 'jp', name: 'Japan' },
    { code: 'jo', name: 'Jordanien' },
    { code: 'kz', name: 'Kasachstan' },
    { code: 'ke', name: 'Kenia' },
    { code: 'ki', name: 'Kiribati' },
    { code: 'kp', name: 'Korea, Demokratische Volksrepublik' },
    { code: 'kr', name: 'Korea, Republik' },
    { code: 'kw', name: 'Kuwait' },
    { code: 'kg', name: 'Kirgisistan' },
    { code: 'la', name: 'Laos' },
    { code: 'lv', name: 'Lettland' },
    { code: 'lb', name: 'Libanon' },
    { code: 'ls', name: 'Lesotho' },
    { code: 'lr', name: 'Liberia' },
    { code: 'ly', name: 'Libyen' },
    { code: 'li', name: 'Liechtenstein' },
    { code: 'lt', name: 'Litauen' },
    { code: 'lu', name: 'Luxemburg' },
    { code: 'mo', name: 'Macau' },
    { code: 'mk', name: 'Mazedonien' },
    { code: 'mg', name: 'Madagaskar' },
    { code: 'mw', name: 'Malawi' },
    { code: 'my', name: 'Malaysia' },
    { code: 'mv', name: 'Malediven' },
    { code: 'ml', name: 'Mali' },
    { code: 'mt', name: 'Malta' },
    { code: 'mh', name: 'Marshallinseln' },
    { code: 'mq', name: 'Martinique' },
    { code: 'mr', name: 'Mauretanien' },
    { code: 'mu', name: 'Mauritius' },
    { code: 'yt', name: 'Mayotte' },
    { code: 'mx', name: 'Mexiko' },
    { code: 'fm', name: 'Mikronesien' },
    { code: 'md', name: 'Moldawien' },
    { code: 'mc', name: 'Monaco' },
    { code: 'mn', name: 'Mongolei' },
    { code: 'ms', name: 'Montserrat' },
    { code: 'ma', name: 'Marokko' },
    { code: 'mz', name: 'Mosambik' },
    { code: 'mm', name: 'Myanmar' },
    { code: 'na', name: 'Namibia' },
    { code: 'nr', name: 'Nauru' },
    { code: 'np', name: 'Nepal' },
    { code: 'nl', name: 'Niederlande' },
    { code: 'an', name: 'Niederländische Antillen' },
    { code: 'nc', name: 'Neukaledonien' },
    { code: 'nz', name: 'Neuseeland' },
    { code: 'ni', name: 'Nicaragua' },
    { code: 'ne', name: 'Niger' },
    { code: 'ng', name: 'Nigeria' },
    { code: 'nu', name: 'Niue' },
    { code: 'nf', name: 'Norfolkinsel' },
    { code: 'mp', name: 'Nördliche Marianen' },
    { code: 'no', name: 'Norwegen' },
    { code: 'om', name: 'Oman' },
    { code: 'pk', name: 'Pakistan' },
    { code: 'pw', name: 'Palau' },
    { code: 'ps', name: 'Palästinensische Gebiete' },
    { code: 'pa', name: 'Panama' },
    { code: 'pg', name: 'Papua-Neuguinea' },
    { code: 'py', name: 'Paraguay' },
    { code: 'pe', name: 'Peru' },
    { code: 'ph', name: 'Philippinen' },
    { code: 'pn', name: 'Pitcairn' },
    { code: 'pl', name: 'Polen' },
    { code: 'pt', name: 'Portugal' },
    { code: 'pr', name: 'Puerto Rico' },
    { code: 'qa', name: 'Katar' },
    { code: 're', name: 'Réunion' },
    { code: 'ro', name: 'Rumänien' },
    { code: 'ru', name: 'Russland' },
    { code: 'rw', name: 'Ruanda' },
    { code: 'sh', name: 'St. Helena' },
    { code: 'kn', name: 'St. Kitts und Nevis' },
    { code: 'lc', name: 'St. Lucia' },
    { code: 'pm', name: 'St. Pierre und Miquelon' },
    { code: 'vc', name: 'St. Vincent und die Grenadinen' },
    { code: 'ws', name: 'Samoa' },
    { code: 'sm', name: 'San Marino' },
    { code: 'st', name: 'Sao Tome und Principe' },
    { code: 'sa', name: 'Saudi-Arabien' },
    { code: 'sn', name: 'Senegal' },
    { code: 'cs', name: 'Serbien und Montenegro' },
    { code: 'sc', name: 'Seychellen' },
    { code: 'sl', name: 'Sierra Leone' },
    { code: 'sg', name: 'Singapur' },
    { code: 'sk', name: 'Slowakei' },
    { code: 'si', name: 'Slowenien' },
    { code: 'sb', name: 'Salomonen' },
    { code: 'so', name: 'Somalia' },
    { code: 'za', name: 'Südafrika' },
    { code: 'gs', name: 'Südgeorgien und die Südlichen Sandwichinseln' },
    { code: 'es', name: 'Spanien' },
    { code: 'lk', name: 'Sri Lanka' },
    { code: 'sd', name: 'Sudan' },
    { code: 'sr', name: 'Suriname' },
    { code: 'sj', name: 'Svalbard und Jan Mayen' },
    { code: 'sz', name: 'Swasiland' },
    { code: 'se', name: 'Schweden' },
    { code: 'ch', name: 'Schweiz' },
    { code: 'sy', name: 'Syrien' },
    { code: 'tw', name: 'Taiwan' },
    { code: 'tj', name: 'Tadschikistan' },
    { code: 'tz', name: 'Tansania' },
    { code: 'th', name: 'Thailand' },
    { code: 'tl', name: 'Timor-Leste' },
    { code: 'tg', name: 'Togo' },
    { code: 'tk', name: 'Tokelau' },
    { code: 'to', name: 'Tonga' },
    { code: 'tt', name: 'Trinidad und Tobago' },
    { code: 'tn', name: 'Tunesien' },
    { code: 'tr', name: 'Türkei' },
    { code: 'tm', name: 'Turkmenistan' },
    { code: 'tc', name: 'Turks- und Caicosinseln' },
    { code: 'tv', name: 'Tuvalu' },
    { code: 'ug', name: 'Uganda' },
    { code: 'ua', name: 'Ukraine' },
    { code: 'ae', name: 'Vereinigte Arabische Emirate' },
    { code: 'gb', name: 'Vereinigtes Königreich' },
    { code: 'us', name: 'Vereinigte Staaten' },
    { code: 'um', name: 'United States Minor Outlying Islands' },
    { code: 'uy', name: 'Uruguay' },
    { code: 'uz', name: 'Usbekistan' },
    { code: 'vu', name: 'Vanuatu' },
    { code: 've', name: 'Venezuela' },
    { code: 'vn', name: 'Vietnam' },
    { code: 'vg', name: 'Jungferninseln, Britische' },
    { code: 'vi', name: 'Jungferninseln, Amerikanische' },
    { code: 'wf', name: 'Wallis und Futuna' },
    { code: 'eh', name: 'Westsahara' },
    { code: 'ye', name: 'Jemen' },
    { code: 'zm', name: 'Sambia' },
    { code: 'zw', name: 'Simbabwe' }
];

var languages = [
    { name: "Englisch", code: "en" },
    { name: "Deutsch", code: "de" },
    { name: "Französisch", code: "fr" },
    { name: "Spanisch", code: "es" },
    { name: "Italienisch", code: "it" },
    { name: "Portugiesisch", code: "pt" },
    { name: "Japanisch", code: "ja" },
    { name: "Chinesisch (Vereinfacht)", code: "zh-CN" },
    { name: "Chinesisch (Traditionell)", code: "zh-TW" },
    { name: "Koreanisch", code: "ko" },
    { name: "Russisch", code: "ru" },
    { name: "Arabisch", code: "ar" },
    { name: "Hindi", code: "hi" },
    { name: "Niederländisch", code: "nl" },
    { name: "Polnisch", code: "pl" },
    { name: "Türkisch", code: "tr" },
    { name: "Schwedisch", code: "sv" },
    { name: "Dänisch", code: "da" },
    { name: "Norwegisch", code: "no" },
    { name: "Finnisch", code: "fi" },
    { name: "Griechisch", code: "el" },
    { name: "Hebräisch", code: "he" },
    { name: "Thailändisch", code: "th" },
    { name: "Vietnamesisch", code: "vi" },
    { name: "Indonesisch", code: "id" },
    { name: "Malaiisch", code: "ms" },
    { name: "Tschechisch", code: "cs" },
    { name: "Ungarisch", code: "hu" },
    { name: "Rumänisch", code: "ro" },
    { name: "Ukrainisch", code: "uk" }
].sort((a, b) => a.name.localeCompare(b.name));

var googleDomains = [
    { value: "google.com", label: "www.google.com" },
    { value: "google.ad", label: "www.google.ad" },
    { value: "google.ae", label: "www.google.ae" },
    { value: "google.am", label: "www.google.am" },
    { value: "google.as", label: "www.google.as" },
    { value: "google.at", label: "www.google.at" },
    { value: "google.az", label: "www.google.az" },
    { value: "google.ba", label: "www.google.ba" },
    { value: "google.be", label: "www.google.be" },
    { value: "google.bf", label: "www.google.bf" },
    { value: "google.bg", label: "www.google.bg" },
    { value: "google.bi", label: "www.google.bi" },
    { value: "google.bj", label: "www.google.bj" },
    { value: "google.bs", label: "www.google.bs" },
    { value: "google.by", label: "www.google.by" },
    { value: "google.ca", label: "www.google.ca" },
    { value: "google.cat", label: "www.google.cat" },
    { value: "google.cd", label: "www.google.cd" },
    { value: "google.cf", label: "www.google.cf" },
    { value: "google.cg", label: "www.google.cg" },
    { value: "google.ch", label: "www.google.ch" },
    { value: "google.ci", label: "www.google.ci" },
    { value: "google.cl", label: "www.google.cl" },
    { value: "google.cm", label: "www.google.cm" },
    { value: "google.co.ao", label: "www.google.co.ao" },
    { value: "google.co.bw", label: "www.google.co.bw" },
    { value: "google.co.ck", label: "www.google.co.ck" },
    { value: "google.co.cr", label: "www.google.co.cr" },
    { value: "google.co.id", label: "www.google.co.id" },
    { value: "google.co.il", label: "www.google.co.il" },
    { value: "google.co.im", label: "www.google.co.im" },
    { value: "google.co.in", label: "www.google.co.in" },
    { value: "google.co.je", label: "www.google.co.je" },
    { value: "google.co.jp", label: "www.google.co.jp" },
    { value: "google.co.ke", label: "www.google.co.ke" },
    { value: "google.co.kr", label: "www.google.co.kr" },
    { value: "google.co.ls", label: "www.google.co.ls" },
    { value: "google.co.ma", label: "www.google.co.ma" },
    { value: "google.co.mw", label: "www.google.co.mw" },
    { value: "google.co.mz", label: "www.google.co.mz" },
    { value: "google.co.nz", label: "www.google.co.nz" },
    { value: "google.co.pn", label: "www.google.co.pn" },
    { value: "google.co.th", label: "www.google.co.th" },
    { value: "google.co.tt", label: "www.google.co.tt" },
    { value: "google.co.tz", label: "www.google.co.tz" },
    { value: "google.co.ug", label: "www.google.co.ug" },
    { value: "google.co.uk", label: "www.google.co.uk" },
    { value: "google.co.uz", label: "www.google.co.uz" },
    { value: "google.co.ve", label: "www.google.co.ve" },
    { value: "google.co.vi", label: "www.google.co.vi" },
    { value: "google.co.za", label: "www.google.co.za" },
    { value: "google.co.zm", label: "www.google.co.zm" },
    { value: "google.co.zw", label: "www.google.co.zw" },
    { value: "google.com.af", label: "www.google.com.af" },
    { value: "google.com.ag", label: "www.google.com.ag" },
    { value: "google.com.ai", label: "www.google.com.ai" },
    { value: "google.com.ar", label: "www.google.com.ar" },
    { value: "google.com.au", label: "www.google.com.au" },
    { value: "google.com.bd", label: "www.google.com.bd" },
    { value: "google.com.bh", label: "www.google.com.bh" },
    { value: "google.com.bn", label: "www.google.com.bn" },
    { value: "google.com.bo", label: "www.google.com.bo" },
    { value: "google.com.br", label: "www.google.com.br" },
    { value: "google.com.bz", label: "www.google.com.bz" },
    { value: "google.com.co", label: "www.google.com.co" },
    { value: "google.com.cu", label: "www.google.com.cu" },
    { value: "google.com.cy", label: "www.google.com.cy" },
    { value: "google.com.do", label: "www.google.com.do" },
    { value: "google.com.ec", label: "www.google.com.ec" },
    { value: "google.com.eg", label: "www.google.com.eg" },
    { value: "google.com.et", label: "www.google.com.et" },
    { value: "google.com.fj", label: "www.google.com.fj" },
    { value: "google.com.gh", label: "www.google.com.gh" },
    { value: "google.com.gi", label: "www.google.com.gi" },
    { value: "google.com.gr", label: "www.google.com.gr" },
    { value: "google.com.gt", label: "www.google.com.gt" },
    { value: "google.com.hk", label: "www.google.com.hk" },
    { value: "google.com.jm", label: "www.google.com.jm" },
    { value: "google.com.kh", label: "www.google.com.kh" },
    { value: "google.com.kw", label: "www.google.com.kw" },
    { value: "google.com.kz", label: "www.google.com.kz" },
    { value: "google.com.lb", label: "www.google.com.lb" },
    { value: "google.com.lv", label: "www.google.com.lv" },
    { value: "google.com.ly", label: "www.google.com.ly" },
    { value: "google.com.mt", label: "www.google.com.mt" },
    { value: "google.com.mw", label: "www.google.com.mw" },
    { value: "google.com.mx", label: "www.google.com.mx" },
    { value: "google.com.my", label: "www.google.com.my" },
    { value: "google.com.na", label: "www.google.com.na" },
    { value: "google.com.nf", label: "www.google.com.nf" },
    { value: "google.com.ng", label: "www.google.com.ng" },
    { value: "google.com.ni", label: "www.google.com.ni" },
    { value: "google.com.np", label: "www.google.com.np" },
    { value: "google.com.om", label: "www.google.com.om" },
    { value: "google.com.pa", label: "www.google.com.pa" },
    { value: "google.com.pe", label: "www.google.com.pe" },
    { value: "google.com.ph", label: "www.google.com.ph" },
    { value: "google.com.pk", label: "www.google.com.pk" },
    { value: "google.com.pl", label: "www.google.com.pl" },
    { value: "google.com.pr", label: "www.google.com.pr" },
    { value: "google.com.py", label: "www.google.com.py" },
    { value: "google.com.qa", label: "www.google.com.qa" },
    { value: "google.com.ru", label: "www.google.com.ru" },
    { value: "google.com.sa", label: "www.google.com.sa" },
    { value: "google.com.sb", label: "www.google.com.sb" },
    { value: "google.com.sg", label: "www.google.com.sg" },
    { value: "google.com.sl", label: "www.google.com.sl" },
    { value: "google.com.sv", label: "www.google.com.sv" },
    { value: "google.com.tj", label: "www.google.com.tj" },
    { value: "google.com.tn", label: "www.google.com.tn" },
    { value: "google.com.tr", label: "www.google.com.tr" },
    { value: "google.com.tt", label: "www.google.com.tt" },
    { value: "google.com.tw", label: "www.google.com.tw" },
    { value: "google.com.ua", label: "www.google.com.ua" },
    { value: "google.com.uy", label: "www.google.com.uy" },
    { value: "google.com.vc", label: "www.google.com.vc" },
    { value: "google.com.ve", label: "www.google.com.ve" },
    { value: "google.com.vn", label: "www.google.com.vn" },
    { value: "google.cv", label: "www.google.cv" },
    { value: "google.cz", label: "www.google.cz" },
    { value: "google.de", label: "www.google.de" },
    { value: "google.dj", label: "www.google.dj" },
    { value: "google.dk", label: "www.google.dk" },
    { value: "google.dm", label: "www.google.dm" },
    { value: "google.dz", label: "www.google.dz" },
    { value: "google.ee", label: "www.google.ee" },
    { value: "google.es", label: "www.google.es" },
    { value: "google.fi", label: "www.google.fi" },
    { value: "google.fm", label: "www.google.fm" },
    { value: "google.fr", label: "www.google.fr" },
    { value: "google.ga", label: "www.google.ga" },
    { value: "google.ge", label: "www.google.ge" },
    { value: "google.gg", label: "www.google.gg" },
    { value: "google.gl", label: "www.google.gl" },
    { value: "google.gm", label: "www.google.gm" },
    { value: "google.gp", label: "www.google.gp" },
    { value: "google.gr", label: "www.google.gr" },
    { value: "google.gy", label: "www.google.gy" },
    { value: "google.hk", label: "www.google.hk" },
    { value: "google.hn", label: "www.google.hn" },
    { value: "google.hr", label: "www.google.hr" },
    { value: "google.ht", label: "www.google.ht" },
    { value: "google.hu", label: "www.google.hu" },
    { value: "google.ie", label: "www.google.ie" },
    { value: "google.iq", label: "www.google.iq" },
    { value: "google.is", label: "www.google.is" },
    { value: "google.it", label: "www.google.it" },
    { value: "google.je", label: "www.google.je" },
    { value: "google.jo", label: "www.google.jo" },
    { value: "google.jp", label: "www.google.jp" },
    { value: "google.kg", label: "www.google.kg" },
    { value: "google.ki", label: "www.google.ki" },
    { value: "google.kz", label: "www.google.kz" },
    { value: "google.la", label: "www.google.la" },
    { value: "google.li", label: "www.google.li" },
    { value: "google.lk", label: "www.google.lk" },
    { value: "google.lt", label: "www.google.lt" },
    { value: "google.lu", label: "www.google.lu" },
    { value: "google.lv", label: "www.google.lv" },
    { value: "google.md", label: "www.google.md" },
    { value: "google.me", label: "www.google.me" },
    { value: "google.mg", label: "www.google.mg" },
    { value: "google.mk", label: "www.google.mk" },
    { value: "google.ml", label: "www.google.ml" },
    { value: "google.mn", label: "www.google.mn" },
    { value: "google.ms", label: "www.google.ms" },
    { value: "google.mu", label: "www.google.mu" },
    { value: "google.mv", label: "www.google.mv" },
    { value: "google.mw", label: "www.google.mw" },
    { value: "google.ne", label: "www.google.ne" },
    { value: "google.ne.jp", label: "www.google.ne.jp" },
    { value: "google.nl", label: "www.google.nl" },
    { value: "google.no", label: "www.google.no" },
    { value: "google.nr", label: "www.google.nr" },
    { value: "google.nu", label: "www.google.nu" },
    { value: "google.off.ai", label: "www.google.off.ai" },
    { value: "google.ph", label: "www.google.ph" },
    { value: "google.pl", label: "www.google.pl" },
    { value: "google.pn", label: "www.google.pn" },
    { value: "google.ps", label: "www.google.ps" },
    { value: "google.pt", label: "www.google.pt" },
    { value: "google.ro", label: "www.google.ro" },
    { value: "google.rs", label: "www.google.rs" },
    { value: "google.ru", label: "www.google.ru" },
    { value: "google.rw", label: "www.google.rw" },
    { value: "google.sc", label: "www.google.sc" },
    { value: "google.se", label: "www.google.se" },
    { value: "google.sg", label: "www.google.sg" },
    { value: "google.sh", label: "www.google.sh" },
    { value: "google.si", label: "www.google.si" },
    { value: "google.sk", label: "www.google.sk" },
    { value: "google.sm", label: "www.google.sm" },
    { value: "google.sn", label: "www.google.sn" },
    { value: "google.so", label: "www.google.so" },
    { value: "google.st", label: "www.google.st" },
    { value: "google.td", label: "www.google.td" },
    { value: "google.tg", label: "www.google.tg" },
    { value: "google.tk", label: "www.google.tk" },
    { value: "google.tl", label: "www.google.tl" },
    { value: "google.tm", label: "www.google.tm" },
    { value: "google.tn", label: "www.google.tn" },
    { value: "google.to", label: "www.google.to" },
    { value: "google.tt", label: "www.google.tt" },
    { value: "google.us", label: "www.google.us" },
    { value: "google.vg", label: "www.google.vg" },
    { value: "google.vn", label: "www.google.vn" },
    { value: "google.vu", label: "www.google.vu" },
    { value: "google.ws", label: "www.google.ws" }
].sort((a, b) => a.label.localeCompare(b.label));
